---
 - name: Download Consul-template Binary Package
   uri:
    method: "GET" 
    url: "{{ download_addr }}"
    dest: "{{ temp_path }}/{{ name }}.zip"
    creates: "{{temp_path}}/{{ name }}.zip"

 - name: Installing Consul-template
   unarchive:
    src: "{{ temp_path }}/{{ name }}.zip"
    dest: "{{ install_path }}"
    copy: no
    creates: "{{ install_path }}/{{ name }}"
