---
 - hosts: all
   roles:
    #- role: add_users
    #- role: set_repo
    #- role: install_base_soft
    #- role: set_time
    #- role: set_limits
    #- role: set_sysctl
    #- role: set_sshd
    - role: set_others
   
 - hosts: IDC
   roles:
    - role: set_nameserver
...
