---
 - hosts: IDC
   roles:
    #- role: set_nameserver
    #- role: set_sysctl

 - hosts: all
   roles:
    #- role: set_sshd
    #- role: set_repo
    #- role: install_base_soft
    #- role: set_time
    #- role: add_users
    #- role: set_limits
    - role: set_others
...
