---
 - hosts: 
    - IDC
   roles:
    - role: set_nameserver

 - hosts:
    - aliyun
    - vultr
   roles:
    - role: set_repo
    - role: install_base_soft
    - role: set_hostname
    - role: set_sysctl
    - role: set_time
    - role: set_sshd
    - role: set_passwd
    - role: set_limits
    - role: set_rclocal
    - role: disable_service
    - role: update_kernel
...
