---
 - name: Download Logstash Package
   uri: 
    url: "{{ logstash_package_url }}"
    dest: "{{ tempdir }}"
    creates: "{{ tempdir }}/{{ logstash_package_fullname }}"

 - block:
    - debug:
       msg: "Install Logstash"
    - unarchive:
       src: "{{ tempdir }}/{{ logstash_package_fullname }}" 
       dest: "{{ tempdir }}"
       copy: no
       creates: "{{ tempdir }}/{{ logstash_package_name }}"
    - synchronize:
       src: "{{ tempdir }}/{{ logstash_package_name }}/"
       dest: "{{ logstash_basedir }}"
      delegate_to: "{{ inventory_hostname }}"
    - file:
       path: "{{ logstash_basedir }}/{{ item }}"
       state: directory
      with_items:
       - "sincedb"
       - "patterns"
       - "conf"
       - "logs"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ logstash_basedir }}/{{ item }}"
      with_items:
       - "conf/redis.conf"
    - synchronize:
       src: "patterns/"
       dest: "{{ logstash_basedir }}/patterns"

 - block:
    - debug:
       msg: "Setup Logstash Auto Start"
    - template:
        src: "logstash.service.j2"
        dest: "/lib/systemd/system/logstash.service"
    - command: "systemctl enable logstash"
       


...
