---
 - name: Download Logstash Package
   uri:
    url: "{{ package_url }}"
    dest: "{{ tempdir }}"
    creates: "{{ tempdir }}/{{ package_fullname }}"

 - name: Install Logstash
   yum: 
    name: "{{ tempdir }}/{{ package_fullname }}"
    state: present

 - block:
    - debug:
       msg: "Configuration"
    - file:
       path: "{{ confdir }}/{{ item }}"
       state: directory
      with_items:
       - "patterns"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ confdir }}/{{ item }}"
      with_items:
       - "conf.d/redis.conf"
    - synchronize:
       src: "patterns/"
       dest: "{{ confdir }}/patterns"

 - block:
    - debug:
       msg: "Setup Logstash Auto Start"
    - command: "systemctl enable logstash"
       


...
