---
 - name: Install Logstash
   yum: 
    name: "{{ package_url }}"
    state: present

 - block:
    - debug:
       msg: "Configuration"
    - file:
       path: "{{ confdir }}/{{ item }}"
       state: directory
      with_items:
       - "patterns"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ confdir }}/{{ item }}"
      with_items:
       - "conf.d/kafka.conf"
    - synchronize:
       src: "patterns/"
       dest: "{{ confdir }}/patterns"

 - block:
    - debug:
       msg: "Setup Logstash Auto Start"
    - command: "systemctl enable logstash"
       


...
