---
 - name: Download Logstash Package
   uri: 
    url: "{{ logstash_package_url }}"
    dest: "{{ tempdir }}"
    creates: "{{ tempdir }}/{{ logstash_package_fullname }}"

 - block:
    - debug:
       msg: "Install Logstash"
    - unarchive:
       src: "{{ tempdir }}/{{ logstash_package_fullname }}" 
       dest: "{{ tempdir }}"
       copy: no
       creates: "{{ tempdir }}/{{ logstash_package_name }}"
#    - command: "rsync -avP {{ tempdir }}/{{ logstash_package_name }} {{logstash_basedir}}"
    - synchronize:
       src: "{{ tempdir }}/{{ logstash_package_name }}/"
       dest: "{{logstash_basedir}}"
      delegate_to: "{{ inventory_hostname }}"


...
