---
 - name: Add Git User Group
   group:
    name: "{{ git_user.name }}"
    gid: "{{ git_user.id }}"
    state: present
    system: yes

 - name: Add Git User
   user:
    name: "{{ git_user.name }}"
    group: "{{ git_user.name }}"
    uid: "{{ git_user.id }}"
    createhome: yes
    comment: "{{ git_user.comment }}"
    shell: /sbin/nologin
    state: present
    system: yes

 - name: Download Gogs Binary Package
   uri:
    method: "GET"
    url: "{{ gogs_url }}"
    dest: "/tmp/{{ gogs_pkg_name }}"
    creates: "/tmp/{{ gogs_pkg_name }}"

 - name: Create Gogs Install Directory
   file:
    path:  "{{ gogs_install_path }}"
    state: directory

 - name: Create Gogs Data And Logs Directory
   file:
    path: "{{ item }}"
    state: directory
    owner: "{{ git_user.name }}"
    group: "{{ git_user.name  }}"
   with_items:
    - "{{ gogs_data_dir }}"
    - "{{ gogs_logs_dir }}"

 - name: Installing Gogs
   unarchive:
    src: "/tmp/{{ gogs_pkg_name }}"
    dest: "{{ gogs_install_path }}"
    copy: no
    creates: "{{ gogs_install_path }}/{{ gogs_name }}"
    owner: "{{ git_user.name }}"
    group: "{{ git_user.name  }}"

 - name: Set Systemd
   template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
   with_items:
    - "gogs.service"
