---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install PHP
   yum:
    name: "{{ php_package_url }}"
    state: present

 - block:
    - debug:
       msg: Git PHP Conf
    - file: 
       path: "{{ php_install_dir }}/etc"
       state: absent
    - git: 
       repo: "{{ php_conf_url }}"
       dest: "{{ php_install_dir }}/etc"
       clone: yes

 - name: Generate Logs Directory
   file:
    path: "{{ php_logs_dir }}"
    owner: "{{ php_user }}"
    group: "{{ php_user }}"
    recurse: yes
    state: directory

 - name: Start Daemon When System Boot
   blockinfile: 
    block: "{{ php_install_dir }}/sbin/php-fpm"
    dest: /etc/rc.d/rc.local       

 - name: Set Environment PATH
   blockinfile:
    block: "export PATH={{ php_install_dir }}/bin:$PATH"
    dest: /etc/.bash_profile

...
