---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Mysql
   yum:
    name: "{{ mysql_package_url }}"
    state: present

 - name: Add Mysql Libs Configuration
   template:
    src: "lib_mysql.conf.j2"
    dest: "/etc/ld.so.conf.d/mysql.conf"

 - name: Ldconfig
   shell: ldconfig

 - name: Set Environment PATH
   blockinfile: 
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR MYSQL"
    block: "export PATH={{ mysql_install_dir }}/bin:$PATH"
    dest: /root/.bash_profile

 - block:
    - debug:
       msg: Initail Mysql Data Directory
    - file:
       path: "{{ mysql_datadir }}/{{ mysql_port }}/{{ item }}"
       owner: "{{ mysql_user }}"
       group: "{{ mysql_user }}"
       recurse: yes
       state: directory
      with_items:
       - data
       - logs/binlog
       - logs/relaylog
    - template:
       src: "{{ item.name }}.j2"
       dest: "{{ mysql_datadir }}/{{ mysql_port }}/{{ item.name }}"
       owner: "{{ mysql_user }}"
       group: "{{ mysql_user }}"
       mode: "{{ item.mode }}"
      with_items:
       - {name: my.cnf, mode: 600}
       - {name: mysqld, mode: 700}
    - shell: "{{ mysql_install_dir }}/scripts/mysql_install_db --defaults-file={{ mysql_datadir }}/{{ mysql_port }}/my.cnf --basedir={{ mysql_install_dir }}"

 - name: Start Daemon When System Boot
   blockinfile: 
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR MYSQL OF PORT {{ mysql_port }}"
    block: "{{ mysql_datadir }}/{{ mysql_port }}/mysqld start"
    dest: /etc/rc.d/rc.local

...
