---
 - name: Install Mysql
   yum:
    name: "{{ mysql_package_url }}"
    state: present

 - block:
    - debug:
       msg: Generate Mysql Data Directory
    - file:
       path: "{{ mysql_datadir }}/{{ mysql_port }}/{{ item }}"
       state: directory
       owner: "{{ mysql_user }}"
       group: "{{ mysql_user }}"
      with_items:
       - data
       - logs/binlog
       - logs/relaylog
    - template:
       src: "{{ item.name }}.j2"
       dest: "{{ mysql_datadir }}/{{ mysql_port }}/{{ item.name }}"
       owner: "{{ mysql_user }}"
       group: "{{ mysql_user }}"
       mode: "{{ item.mode }}"
      with_items:
       - {name: my.cnf, mode: 600}
       - {name: mysqld, mode: 700}
    - shell: "{{ mysql_install_dir }}/scripts/mysql_install_db --defaults-file={{ mysql_datadir }}/{{ mysql_port }}/my.cnf --basedir={{ mysql_install_dir }}"

 - name: Install Mysql Tools
   yum:
    name: "{{ item }}"
    state: present
   with_items: "{{ tools_package_url }}"

 - name: Start Daemon When System Boot
   shell: echo "{{ mysql_datadir }}/{{ mysql_port }}/mysqld start" >> /etc/rc.local

 - name: Ldconfig Mysql Libs
   shell: echo "{{ mysql_install_dir }}/lib" >> /etc/ld.so.conf.d/mysql.conf && ldconfig

 - name: Export PATH
   shell: echo "export PATH={{ mysql_install_dir }}/bin:$PATH" >> /root/.bash_profile

...
