---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Add Mysql User Group
   group: 
    name: "{{ mysql_user.name }}" 
    gid: "{{ mysql_user.id }}" 
    state: present 
    system: yes

 - name: Add Mysql User
   user: 
    name: "{{ mysql_user.name }}" 
    group: "{{ mysql_user.name }}" 
    uid: "{{ mysql_user.id }}" 
    createhome: no 
    comment: "{{ mysql_user.comment }}" 
    shell: /sbin/nologin 
    state: present 
    system: yes

 - name: Installing Mysql
   yum:
    name: "{{ mysql_package_url }}"
    state: present
   tags:
    - installing

 - name: Add Mysql Libs Configuration
   template:
    src: "lib_mysql.conf.j2"
    dest: "/etc/ld.so.conf.d/mysql.conf"

 - name: Ldconfig
   shell: ldconfig

 - name: Set Environment PATH
   blockinfile: 
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR MYSQL"
    block: "export PATH={{ mysql_install_dir }}/bin:$PATH"
    dest: /etc/profile

 - block:
    - debug:
       msg: Initail Mysql Data Directory
    - file:
       path: "{{ mysql_datadir }}/{{ mysql_port }}/{{ item }}"
       owner: "{{ mysql_user.name }}"
       group: "{{ mysql_user.name }}"
       recurse: yes
       state: directory
      with_items:
       - data
       - logs/binlog
       - logs/relaylog
    - template:
       src: "{{ item.name }}.j2"
       dest: "{{ mysql_datadir }}/{{ mysql_port }}/{{ item.name }}"
       owner: "{{ mysql_user.name }}"
       group: "{{ mysql_user.name }}"
       mode: "{{ item.mode }}"
      with_items:
       - {name: my.cnf, mode: 600}
       - {name: mysqld, mode: 700}
   tags:
    - instance

 - name: Start Daemon When System Boot
   blockinfile: 
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR MYSQL OF PORT {{ mysql_port }}"
    block: "{{ mysql_datadir }}/{{ mysql_port }}/mysqld start"
    dest: /etc/rc.d/rc.local

 - name: Include Percona_tools Roles
   include_role:
    name: percona_tools 
...
