---
 - name: Close Selinux
   selinux: 
    state: disabled

 - name: Disable Firewall On Centos 6
   service: 
    name: iptables
    state: stopped
    enabled: no
   when: ansible_distribution_major_version == "6"

 - name: Disable Firewall On Centos 7
   service: 
    name: firewalld
    state: stopped
    enabled: no
   when: ansible_distribution_major_version == "7"

 - name: Disable Postfix
   service:
    name: postfix
    state: stopped
    enabled: no

 - name: Chmod /etc/rc.d/rc.local
   file: 
    path: '/etc/rc.d/rc.local'
    mode: "u+rwx"
    state: file

 - name: Enable rc-local service
   service:
    name: rc-local
    enabled: yes

 - block: 
    - debug:
       msg: "Change PYPI Source"
    - file:
       path: "~/.pip"
       state: directory
    - copy:
       src: "pip.conf"
       dest: "~/.pip/pip.conf"

 - name: Update Pip
   pip:
    name: "pip"
    state: latest 

 - name: Update Kernel
   yum:
    name: "*"
    state: latest 

 - name: Reboot System
   command: /sbin/shutdown -r +1
   async: 0
   poll: 0

   # - name: Wait_for Reboot
   #wait_for_connection:
   # delay: 60
   # sleep: 5
   # timeout: 300
   # state: started

 - name: Wait_for Reboot
   wait_for:
    port: 22
    host: "{{ansible_ssh_host|default(inventory_hostname)}}"
    delay: 10
    sleep: 5
    timeout: 300
    state: started
   connection: local

