---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Svn Update Zabbix-agent Configuration
   subversion:
    repo: "{{ SVN_ADDR }}"
    username: "{{ SVN_USER }}"
    password: "{{ SVN_PASSWD }}"
    dest: /etc/zabbix/zabbix_agentd.d
    force: yes
   notify:
    - Restart Zabbix-agent
...
