---
 - name: Add Es Groups
   group:
    name: "{{ item.user }}"
    gid: "{{ item.id }}"
    state: present
    system: yes
   with_items: "{{ users }}"

 - name: Add Es Users
   user:
    name: "{{ item.user }}"
    group: "{{ item.user }}"
    uid: "{{ item.id }}"
    createhome: no
    comment: "{{ item.comment }}"
    shell: /sbin/nologin
    state: present
    system: yes
   with_items: "{{ users }}"

 - name: Unlimit Mlockall
   pam_limits:
    domain: "*"
    limit_item: "{{ item.item }}"
    limit_type: "{{ item.type }}"
    value: "{{ item.value }}"
   with_items:
    - {item: memlock, type: -, value: unlimited}

 - name: Download ES Package
   get_url: 
    url: "{{ package_url }}"
    dest: "{{ tempdir }}/{{ fullname }}"

 - block:
    - debug:
       msg: "Install ES"
    - unarchive:
       src: "{{ tempdir }}/{{ fullname }}" 
       dest: "{{ tempdir }}"
       owner: "{{ users.0.user }}"
       group: "{{ users.0.user }}"
       copy: no
       creates: "{{ tempdir }}/{{ name }}-{{ version }}"
    - synchronize:
       src: "{{ tempdir }}/{{ name }}-{{ version }}/"
       dest: "{{ basedir }}"
      delegate_to: "{{ inventory_hostname }}"
    - template:
       src: "{{ item }}.j2"
       dest: "{{ basedir }}/{{ item }}"
      with_items:
       - "config/elasticsearch.yml"
       - "config/jvm.options"
    - file:
       path: "{{ item }}"
       owner: "{{ users.0.user }}"
       group: "{{ users.0.user }}"
       recurse: yes
       state: directory
      with_items: "{{ datadir }}"

 - block:
    - debug:
       msg: "Setup ES Auto Start"
    - template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
       - "elasticsearch.service"
    - shell: "systemctl enable elasticsearch"
...
