---
 - name: Add Authorized_keys
   authorized_key:
    key: "{{ lookup('file', '{{ item }}.pub') }}"
    user: root
    state: present
   with_items: "{{ users }}"
   when: operation == "add"

 - name: Del Authorized_keys
   authorized_key:
    key: "{{ lookup('file', '{{ item }}.pub') }}"
    user: root
    state: absent
   with_items: "{{ users }}"
   when: operation == "del"
...
