---
 - name: Install Dependent Packages
   yum:
   name: "{{ item }}"
   state: present
   with_items:
    - gcc
    - pcre-devel
    - zlib-devel
    - openssl-devel

 - name: Make Temp Directory
   file: 
    path: /tmp/nginx/
    state: directory

 - name: Get Nginx Source Code
   uri:
    url: http://download.zhangshangduobao.net/Packages/nginx/nginx-{{ Nversion }}.tar.gz
    dest: /tmp/
    creates:

 - name: 
