---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Nginx
   yum:
    name: "{{ nginx_package_url }}"
    state: present
 
 - block:
    - debug:
       msg: Get Nginx Conf
    - file: 
       path: "{{ nginx_install_dir }}/conf"
       state: absent
    - git: 
       repo: "{{ nginx_conf_url }}"
       dest: "{{ nginx_install_dir }}/conf"
       clone: yes
    - copy:
       src: default.htpasswd
       dest: "{{ nginx_install_dir }}/conf/setup/auth/htpasswd/"

 - name: Link Nginx Directory
   file:
    src: "{{ nginx_install_dir }}"
    path: "{{ nginx_link_dir }}"
    state: link

 - name: Start Daemon When System Boot
   blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NGINX"
    block: "{{ nginx_link_dir }}/sbin/nginx"
    dest: /etc/rc.d/rc.local

 - name: Create Logs Dir
   file:
    path: "{{ nginx_logs_dir }}" 
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes
    state: directory

 - name: Set Regular Clean Nginx Logs
   template: 
    src: nginx.logrotate
    dest: /etc/logrotate.d/nginx

 - name: Set Environment PATH 
   blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NGINX"
    block: "export PATH={{ nginx_link_dir }}/sbin:$PATH"
    dest: /root/.bash_profile

...
