---
 - name: Install Dependent Packages
   yum:
    name: "{{ item }}"
    state: present
   with_items:
    - gcc
    - pcre-devel
    - zlib-devel
    - openssl-devel

 - name: Get Nginx Source Code
   uri:
    url: "http://download.zhangshangduobao.net/Packages/nginx/{{ nginx_package }}.tar.gz"
    dest: "{{ build_dir }}"
    creates:

 - block: 
    - debug: 
       msg: Build Nginx Source Code
    - shell: cd "{{ build_dir }}" && tar -xzvf "{{ nginx_package }}".tar.gz
    - shell: cd "{{ build_dir }}/{{ nginx_package }}" && ./configure "--user={{ nginx_user }}" "--group={{ nginx_user }}" "--prefix={{ nginx_install_dir }}" --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-md5=/usr/lib --with-sha1=/usr/lib --with-http_gzip_static_module --with-http_stub_status_module --with-http_realip_module --with-debug
    - shell: cd "{{ build_dir }}/{{ nginx_package }}" && make && make install
 
 - block:
    - debug:
       msg: Git Nginx Conf
    - file: 
       path: "{{ nginx_install_dir }}/conf"
       state: absent
    - git: 
       repo: "{{ nginx_conf_url }}"
       dest: "{{ nginx_install_dir }}/conf"
       clone: yes
        
...
