---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Nginx
   yum:
    name: "{{ nginx_package_url }}"
    state: installed
 
 - block:
    - debug:
       msg: Get Nginx Conf
    - file: 
       path: "{{ nginx_install_dir }}/conf"
       state: absent
    - git: 
       repo: "{{ nginx_conf_url }}"
       dest: "{{ nginx_install_dir }}/conf"
       clone: yes
    - copy:
       src: default.htpasswd
       dest: "{{ nginx_install_dir }}/conf/setup/auth/htpasswd/"

 - name: Start Daemon When System Boot
   shell: echo "{{ nginx_install_dir }}/sbin/nginx" >> /etc/rc.local

 - name: Create Logs Dir
   file:
    path: "{{ nginx_logs_dir }}" 
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes
    state: directory

 - name: Set Regular Clean Nginx Logs
   template: 
    src: nginx.logrotate
    dest: /etc/logrotate.d/nginx

 - name: Set Environment PATH 
   shell: echo "export PATH={{ nginx_install_dir }}/sbin:\$PATH" >> /root/.bash_profile

...
