---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Nginx
   yum:
    name: "{{ nginx_package_url }}"
    state: present
   when: install_naxsi == false
 
 - name: Install Nginx Waf
   yum:
    name: "{{ nginx_naxsi_package_url }}"
    state: present
   when: install_naxsi == true

 - block:
    - debug:
       msg: Get Nginx Conf
    - file: 
       path: "{{ nginx_install_dir }}/conf"
       state: absent
    - git: 
       repo: "{{ nginx_conf_url }}"
       dest: "{{ nginx_install_dir }}/conf"
       clone: yes
    - copy:
       src: default.htpasswd
       dest: "{{ nginx_install_dir }}/conf/setup/auth/htpasswd/"

# - name: Link Nginx Directory
#   file:
#    src: "{{ nginx_install_dir }}"
#    path: "{{ nginx_link_dir }}"
#    state: link

 - name: Start Daemon When System Boot
#   blockinfile:
#    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NGINX"
#    block: "{{ nginx_install_dir }}/sbin/nginx"
#    dest: /etc/rc.d/rc.local
   template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
   notify:
    - Enable Nginx

 - name: Create Logs Dir
   file:
    path: "{{ nginx_logs_dir }}" 
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes
    state: directory

 - name: Set Regular Clean Nginx Logs
   template: 
    src: nginx.logrotate.j2
    dest: /etc/logrotate.d/nginx

 - name: Set Environment PATH 
   blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NGINX"
    block: "export PATH={{ nginx_install_dir }}/sbin:$PATH"
    dest: /etc/profile

...
