---
 - name: Add Basic Repo
   get_url: 
    url: http://mirrors.aliyun.com/repo/Centos-{{ ansible_distribution_major_version }}.repo 
    dest: /etc/yum.repos.d/CentOS-Base.repo 

 - name: Add Rpmforege And Epel Repo
   yum: 
    name: "{{ item }}" 
    state: present
    update_cache: yes
   with_items:
#    - http://mirrors.aliyun.com/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "http://repository.it4i.cz/mirrors/repoforge/redhat/el{{ ansible_distribution_major_version }}/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el{{ ansible_distribution_major_version }}.rf.x86_64.rpm"
 
...
