---
 - name: Delete Old Repo /etc/yum.repos.d/*
   file: path=/etc/yum.repos.d/ state=absent

 - name: Create Dir /etc/yum.repos.d/
   file: path=/etc/yum.repos.d/ state=directory

 - name: Add Basic Repo
   uri: url=http://mirrors.aliyun.com/repo/Centos-{{ ansible_distribution_major_version }}.repo dest=/etc/yum.repos.d/CentOS-Base.repo 

 - name: Add Rpmforege And Epel Repo
   yum: name={{ item }} state=present
   with_items:
    - http://mirrors.aliyun.com/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el{{ ansible_distribution_major_version }}.rf.{{ ansible_machine }}.rpm
 
 - name: Clean Yum Cache
   shell: yum clean all
...
