---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Install Filebeat
   yum: 
    name: "{{ package_url }}"
    state: present

 - name: Copy Templates
   template:
    dest: "/etc/filebeat/filebeat.yml"
    src: "filebeat.yml.j2"

 - name: Set Filebet Auto Start
   service:
    name: "filebeat"
    state: "restarted"
    enabled: yes
...
