---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: Download Filebeat Package
   uri:
    url: "{{ package_url }}"
    dest: "{{ tempdir }}"
    creates: "{{ tempdir }}/{{ name }}"
 - name: Install Filebeat
   yum: 
    name: "{{ tempdir }}/{{ name }}"
    state: present

 - name: Copy Templates
   template:
    dest: "/etc/filebeat/filebeat.yml"
    src: "filebeat.yml.j2"
   notify:
    - Restart Filebeat
...
