---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
    - "secret.yml"

 - name: install dependent packages
   yum: 
    name: unixODBC 
    state: present

 - name: Install Zabbix-agentd On CentOS
   yum: 
    name: "{{ Zabbix_Agent_Package }}"
    state: present

 - name: Copy Zabbix_agent.conf
   template: 
    src: "zabbix_agentd.conf.{{ Mode }}.j2" 
    dest: "/etc/zabbix/zabbix_agentd.conf"

 - name: Delete Old Zabbix_agentd.d Directory
   file:
    path: "/etc/zabbix/zabbix_agentd.d"
    state: absent

 - name: Create Zabbix Monitor Logs Directory
   file:
    path: "/data0/logs/zabbix_agent"
    recurse: yes
    state: directory

 - name: Checkout Zabbix_agentd.d
   git:
    repo: "{{ Monitor_Template_Repo }}"
    dest: "/etc/zabbix/zabbix_agentd.d"
    clone: yes
   notify:
    - Restart Zabbix-agentd
...
