---
 - name: Install Zabbix-agentd On CentOS 7
   yum: 
    name: "{{ Zabbix_Agent_Package }}"
    state: present
   when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'"
   notify:
    - Restart Zabbix-agentd On CentOS 7

 - name: Install Zabbix-agentd On CentOS 6
   yum: 
    name: "{{ Zabbix_Agent_Package }}"
    state: present
   when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'"
   notify:
    - Restart Zabbix-agentd On CentOS 6

 - name: Copy Zabbix_agent.conf
   template: 
    src: zabbix_agentd.conf.{{ Mode }}.j2 
    dest: /etc/zabbix/zabbix_agentd.conf

 - name: Copy Zabbix_agentd.d Directory
   copy:
    src: zabbix_agentd.d
    dest: /etc/zabbix
    directory_mode: directories
...
