---
 - name: Set CentOS 7 Timezone
   shell: timedatectl set-timezone Asia/Shanghai
   when: ansible_distribution_major_version == '7'

 - name: Set CentOS 6 Timezone
   copy: 
    src: timezone.Shanghai 
    dest: /etc/localtime
   when: ansible_distribution_major_version != '7'

 - name: Close Ntpd Service On CentOS 7
   shell: systemctl stop ntpd && systemctl disable ntpd
   when: ansible_distribution_major_version == '7'

 - name: Close Ntpd Service On CentOS 6
   service:
    name: ntpd
    state: stopped
    enabled: no
   when: ansible_distribution_major_version != '7'

 - name: Sync Datetime
   shell: /usr/sbin/ntpdate ntp.api.bz && /usr/sbin/hwclock -w

 - name: Sync Datetime Crontab
   cron: 
    name: "Sync Datetime" 
    state: present  
    hour: 2 
    minute: 15  
    user: root 
    job: "/usr/sbin/ntpdate ntp.api.bz > /dev/null 2>&1;/usr/sbin/hwclock -w > /dev/null 2>&1"
...
