---
 - name: Set Timezone
   timezone:
    name: Asia/Shanghai
   notify:
    - Restart Crond

 - name: Close Ntpd Service
   service:
    name: ntpd
    state: stopped
    enabled: no

 - name: Sync Datetime Crontab
   cron: 
    name: "Sync Datetime" 
    state: present  
    hour: 2 
    minute: 15  
    user: root 
    job: "/usr/sbin/ntpdate 0.centos.pool.ntp.org 1.centos.pool.ntp.org 2.centos.pool.ntp.org 3.centos.pool.ntp.org > /dev/null 2>&1;/usr/sbin/hwclock -w > /dev/null 2>&1"

 - name: Sync Datetime
   shell: /usr/sbin/ntpdate 0.centos.pool.ntp.org 1.centos.pool.ntp.org 2.centos.pool.ntp.org 3.centos.pool.ntp.org && /usr/sbin/hwclock -w
   ignore_errors: True
...
