---
 - name: Install Dependent Packages
   yum:
    name: "{{ item }}"
    state: present
   with_items:
    - jemalloc
    - jemalloc-devel

 - name: Get Redis Source Code
   uri:
    url: "{{ redis_package_url }}"
    dest: "{{ build_dir }}"
    creates: "{{ build_dir }}/{{ redis_package }}.tar.gz"

 - block: 
    - debug: 
       msg: Build Redis Source Code
    - unarchive:
       src: "{{ build_dir }}/{{ redis_package }}.tar.gz"
       dest: "{{ build_dir }}"
       copy: no
       creates: "{{ build_dir }}/{{ redis_package }}"
    - make:
       chdir: "{{ build_dir }}/{{ redis_package }}"
       target: install
       params:
        NUM_THREADS: "{{ ansible_processor_count }}"
        PREFIX: "{{ redis_install_dir }}"
    - file:
       src: "{{ redis_install_dir }}"
       path: "{{ redis_link_dir }}"
       state: link
       force: yes
 
 - name: Export PATH
   blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR REDIS"
    dest: "/root/.bash_profile"
    block: "export PATH={{ redis_link_dir }}/bin:$PATH"

 - name: Generate Redis Instance
   include_role: 
    name: generate_instance
...
