---
tools_package_url: 
 - "{{ package_url_prefix }}/mysql/percona-toolkit-3.0.4-1.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
 - "{{ package_url_prefix }}/mysql/percona-xtrabackup-24-2.4.8-1.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
