---
 - name: Update Kernel
   yum:
    name: "*"
    state: latest 

 - name: Reboot System
   command: /sbin/shutdown -r +1
   async: 0
   poll: 0

 - name: Wait_for Reboot
   wait_for:
    port: 22
    host: "{{ansible_ssh_host|default(inventory_hostname)}}"
    delay: 10
    sleep: 5
    timeout: 300
    state: started
   connection: local

